### ISSUE TITLE
GetWindowRect结果为(0, 0, 0, 0)

### ISSUE THREAD

**Issue by Adonis511** [angelof13/starRailScript#1]
configuration.py中130行 bC = w32.GetWindowRect(startTrain)的输出bC元组为(0, 0, 0, 0)，导致后续有问题。请问这个获取不到窗口真实位置的情况是为什么？

**Comment by angelof13** [comment]
是否是管理员权限运行？
能否补充运行时的报错代码？以便判断是什么情况。
现已知如果后台是VSCode界面，前台窗口为星穹铁道界面，直接alt调出光标点击VSCode的右上角运行按钮，会导致该函数无法找到窗口，但目前无法判断你遇到的是什么情况
