### ISSUE TITLE
have install pyscreeze and sitll throw the exception

### ISSUE THREAD

**Issue by Dawnforcn** [angelof13/starRailScript#2]
![X $LW`TIUX`F0AXGHT(}Z%M](https://github.com/angelof13/starRailScript/assets/22791697/9b91fc20-e47f-481e-9b31-526bf0732083)
我按照这个报错重新install了pyscreeze, 仍然报这个错误

**Comment by angelof13** [comment]
这个问题应该是安装PyAutoGUI的过程中依赖的pyscreeze模块安装失败了。
最简单的办法是，卸载pyscreeze和PyAutoGUI，升级下pip，重新安装PyAutoGUI，安装过程中看下有没有安装失败报错。
因为以来的是特定版本的pyscreeze，如果你手动安装肯定是最新版，版本不对。
