### ISSUE TITLE
脚本卡住

### ISSUE THREAD

**Issue by baokeyuan** [angelof13/starRailScript#3]
前两天更新后经常会出现在雪原战斗结束后无法正确触发fight end 的情况。

**Comment by angelof13** [comment]
请问是多少分辨率下？我需要找下问题

**Comment by angelof13** [comment]
顺便问下，你的客户端最底下的引导是打开的还是关闭的？就是正常界面下最低下的黑色一条，现在脚本要正常运行需要隐藏这个导航栏，因为我这边更新后是默认关闭的，所以小怀疑一手这个问题

**Comment by baokeyuan** [comment]
> 请问是多少分辨率下？我需要找下问题

1280X720,在雅丽洛的雪地白色场景下会出现一直卡fight start 的情况。包括雪原永冬岭和机械聚落，注释掉这几个区域能正常运行。

**Comment by angelof13** [comment]
哦哦，明白了，因为现在是根据对话框旁边的enter标志存在与否来判断的，是使用开始时，区域截图，然后不断识别那里，但是因为各个分辨率下那个标志不是跟着分辨率简单的拉伸，而我的脚本是根据分辨率的比例和一些大概的偏移进行计算的，我只测试了一些较为常选的分辨率，1280*720我没有试，刚刚试了下，而在1280*720下会截取到超出标志的区域，进而影响判断了，我在下次更新，单独修改下1280*720分辨率下的区域坐标
