### ISSUE TITLE
运行到迴星港的时候游戏自动退出

### ISSUE THREAD

**Issue by MinCaoLiu** [angelof13/starRailScript#4]
我用的分辨率是1600×900，娜塔莎在残响回廊会卡在墙角转圈圈，更新1.3之后在迥星港会莫名其妙退游戏，现在我直接把迴星港和残响回廊的代码注释了

**Comment by angelof13** [comment]
残响回廊是在拐角有个突起，那里特别容易卡住，那里想通过确实是一点失误不能有，下次我更新，我改成传送到后面绕过那里，重新写下行动逻辑吧，
至于迴星港退出游戏，应该是电脑问题，长时间运行，可能到了那里会加载的东西多一点？因为我这里没有出现过崩溃，所以不太清楚，不过你可以试下改成1366*768，这个分辨率也是稳定运行，能减轻很大一部分运行压力

**Comment by angelof13** [comment]
是边缘通路的逻辑代码改了，跑了一遍残响回廊，两个号不同设备跑都没有出现卡住的情况，麻烦看下是不是你的残响回廊有门没开？
迴星港的退出游戏也确实没遇到过，如果是退出游戏那就是游戏崩溃，应该是资源占用过高导致的，如果是脚本退出了，麻烦反馈下报错了，因为脚本是模拟键鼠操作，不得知游戏本身是否奔溃，也没有做高频切换地图这种吃资源的操作
如果是游戏崩溃，可以将画质什么的都调到最低，分辨率设置1366*768，反正是脚本在跑，也不用看画面

**Comment by MinCaoLiu** [comment]
> 残响回廊是在拐角有个突起，那里特别容易卡住，那里想通过确实是一点失误不能有，下次我更新，我改成传送到后面绕过那里，重新写下行动逻辑吧， 至于迴星港退出游戏，应该是电脑问题，长时间运行，可能到了那里会加载的东西多一点？因为我这里没有出现过崩溃，所以不太清楚，不过你可以试下改成1366*768，这个分辨率也是稳定运行，能减轻很大一部分运行压力

那我试试，主要是我把洄星港的代码注释掉就没出这个问题了

**Comment by angelof13** [comment]
可以尝试下在1366*768的分辨率下，
角色在迴星港外的任意区域，打开迴星港的地图并将地图缩放到最小，保持在地图界面
再将pathFanding.py中的最下面main函数中的Debug=0【完全执行一次小地图战斗】，然后最下面的一行修改成selectRegion(2,1,0) 【从第3个星球(仙舟)，的第2个区域(迴星港)，的第1段小区域代码开始运行】，最后运行pathFinding.py(!!!不是startRail.py)，看会不会崩溃，在哪崩溃，这个就是小区域调试

**Comment by MinCaoLiu** [comment]
> 

我试了，迴星港不会退了，残响回廊有时候还是会出问题，不过关系不大

**Comment by angelof13** [comment]
OK，确实在不同配置上，运行会有些许差距
