### ISSUE TITLE
想問一下那幾個模組都是甚麼版本,我用那幾個鏡像源都下載不了

### ISSUE THREAD

**Issue by xeivu** [angelof13/starRailScript#5]

**Comment by angelof13** [comment]
都是最新版
pyautogui (0.9.54)
pydirectinput (1.0.4)
pywin32 (306)
opencv-python (4.8.0.76)
不建议自己下包用，pip的安装不仅是安装了包本身，还会安装他们的依赖，如果要自己手动安装，还需要安装他们的依赖，如果用镜像源下载不了，可以尝试将**-i以及后面的**内容删掉，看能否从官方源下载

**Comment by xeivu** [comment]
本來是一直沒讀到fightMarker那張圖片,還以為是甚麼版本的問題,cd資料夾就解決了,另外問下大佬有打算做其他的遠攻人物去帶隊嗎

**Comment by angelof13** [comment]
选择娜塔莎的原因是，
1.脚本运行期间为了防止战斗失败，应该是要带奶或盾的，而娜塔莎作为人人必有的角色比较保险，三月七的保护能力感觉更弱
2.攻击范围大，脚本运行容错高
而如果自己想要换个队伍，只要站场人物选择个远程攻击的非幼女体型的人物都能运行，全地图会漏的怪不超过20个（主要就是那些会移动的怪，近战角色真的不好把握脚本应该走多久，什么时候攻击），
而锄大地的意义其实不在于其他的材料(有点用，但其实锄两三次基本溢出了)，而是角色经验，最好能是4个不满80的角色在锄大地，一轮每个角色能获的经验在4W多，一轮相当于8本紫书，可以把书留给自己喜欢的角色升级，还有一些零散的金币
