### ISSUE TITLE
我找到之前残响回廊那些地图乱走的原因了

### ISSUE THREAD

**Issue by MinCaoLiu** [angelof13/starRailScript#6]
因为在跑动的过程中被怪物打到，强制进战，然后有几步走错了，后面就全走错了，这有办法解决吗

**Comment by angelof13** [comment]
因为在一台电脑上该队伍每天的遇敌时机基本是一致的，出现这种情况，只需要修改pathFinding.py中的残响回廊相应的行动逻辑，将相应的移动逻辑复制一份，将两个移动逻辑中的数值(即时间)之和修改为和之前一样(或略大0.1,0.2)，然后在这之间添加['c'],['cf']（即左键，检测战斗），
怎么找到相应的行动逻辑，可以看控制台中输出的当前行动对应的代码，再到残响回廊的行动逻辑中找到相应的地方就行，
对应代码在pathFinding.py的106-119行，
rNN==0或1或2分别代表在残响回廊中的第1，2，3次传送后的行动逻辑

**Comment by MinCaoLiu** [comment]
我现在是跑完之后把残响回廊和迴星港再单独跑一遍，等看啥时候有时间我来改改，还有就是迴星港有个楼梯旁边的怪，被楼梯扶手挡住了打不到，也得改改试试

**Comment by angelof13** [comment]
> 我现在是跑完之后把残响回廊和迴星港再单独跑一遍，等看啥时候有时间我来改改，还有就是迴星港有个楼梯旁边的怪，被楼梯扶手挡住了打不到，也得改改试试

嗯嗯，因为不同电脑上我的测试是确实有细微差别，在我的笔记本上可能没问题的地方，在我的PC上就可能碰壁，但是同一台设备，运行起来倒是基本一致
