### ISSUE TITLE
工造司的最后一个传送点好像不对

### ISSUE THREAD

**Issue by MinCaoLiu** [angelof13/starRailScript#7]
打完第三个，第四个传送点位点不到

**Comment by angelof13** [comment]
> 打完第三个，第四个传送点位点不到

OK，我看下，能说下你采用的人物是谁？分辨率是多少吗？

**Comment by MinCaoLiu** [comment]
用的娜塔莎，分辨率1366x768

**Comment by angelof13** [comment]
![屏幕截图 2023-11-07 152331](https://github.com/angelof13/starRailScript/assets/19170749/d29bc50b-7f3f-4dae-a285-ed7cf735a6c9)

我这边测试没有问题，你需要看下当第三个传送点的所有行动结束后，人物是否处于这个位置附近

**Comment by MinCaoLiu** [comment]
是在这个位置，但是后面鼠标就点不上了

**Comment by angelof13** [comment]
可以发下，鼠标下一次所在位置，以及configuration.py中regionPoint中的工造司的坐标代码嘛？在文件中直接搜索工造司就能找到

鼠标位置可以先手动跑到这个位置，打开地图，然后将pathFinding.py最下面的DeBug=2改为=1，然后修改selectRegion(#,#,#)为selectRegion(2,5,3)，然后运行pathFingding.py

web中github添加图片，就是添加附件

**Comment by MinCaoLiu** [comment]
![Snipaste_2023-11-07_23-09-39](https://github.com/angelof13/starRailScript/assets/46052741/e49891c0-af53-4b3b-892d-45f89b21943a)
这是debug的结果
![Snipaste_2023-11-07_23-05-46](https://github.com/angelof13/starRailScript/assets/46052741/6c7c3786-c5c1-478c-9b61-0cbc8af1ea27)
这是正常运行的时候运行完第三个坐标之后下一次鼠标的位置

**Comment by angelof13** [comment]
configuration.py中regionPoint，昨天你发的第一遍是对的截图，编辑后的截图是窗口信息
但是没搞明白为什么会在那
不过你可以修改configuration.py中regionPoint工造司的第四个的坐标位置
将游戏设置为1920*1080（如果无法设置，就在1366*768下进行，得到坐标后我帮你算出应该填入的数值）
将人物还是手动跑到那个位置，打开地图
win＋shift＋s区域截图（或从星铁的左上角截图到右下角），
然后用画图（Windows自带的那个）打开，
在左上角选择区域选择画笔（一个虚线框），
将鼠标放到截图中，应该在的那个坐标（就是你截图中右边最上面的传送点），
画图的左下角就有坐标了，那个就是应该填入的坐标

**Comment by MinCaoLiu** [comment]
第一遍那个截图直接截图的你的原代码。
我回去截图试试，全屏可以运行吗，如果不可以，那我用1366*768按比例换算一下是不是就行了，截图只截取游戏画面部分，软件的标题栏啥的不要截进去的对吧

**Comment by angelof13** [comment]
嗯嗯，就是源码部分
不能全屏运行，对，用1366*768比例得到的数据反算一下就行，计算方式就是坐标的x和y分别乘以1.40（1920/1366，1080/768舍去末尾的保留两位小数）
标题栏需要截进去

**Comment by MinCaoLiu** [comment]
奇怪了，是有什么bug吗，鼠标还是点那里，改了坐标还是点那里

**Comment by angelof13** [comment]
如果没有大改过代码了话，完全可以重新下载个最新的代码，然后修改下分辨率配置就好，我这边两个电脑运行是没问题的

**Comment by MinCaoLiu** [comment]
我改过好几个地图的代码，重新下只下cfg和main可以么

**Comment by MinCaoLiu** [comment]
算了，我还是把它注释了吧

**Comment by angelof13** [comment]
可以的，另两个文件不涉及pathFinding的核心逻辑运行，pathFinding的代码只需要对比一下差异，应该就能找出问题，不过我最近有大改几个容易卡住的地图的逻辑，对比起来可能有点乱，只需要对比出问题的地图逻辑附近就行

**Comment by MinCaoLiu** [comment]
不知道是不是我电脑的问题，那个地方就是不行，不管怎么改坐标鼠标位置都不变，我把那一小段代码注释了，不跑那边了，影响也不大
